version: '3'
services:
  db:
    image: postgres:16
    ports:
      - '5048:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: example
    volumes:
      - ./ddl:/docker-entrypoint-initdb.d/

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - env/dev.env
    volumes:
      - ./webapp:/app/webapp
      - ./main.py:/app/main.py
    ports:
      - '8000:8000'
    depends_on:
      - db
